import test from "node:test";
import assert from "node:assert/strict";

import { getOperationalActionPlan } from "./operationalActionPlan.ts";
import type { Chamado } from "../types/chamado";

const now = Date.now();

const chamados: Chamado[] = [
  {
    id: "c1",
    categoria: "operacional",
    empresa_id: "empresa-1",
    supermercado_id: "super-1",
    solicitante_nome: "Ana",
    setor: "Estoque",
    local_exato: null,
    tipo_servico: "Reposição",
    numero_pedido: null,
    cliente: null,
    produto: null,
    quantidade: null,
    itens: [],
    total_solicitado: null,
    total_encontrado: null,
    percentual_atendido: null,
    motivo_incompleto: null,
    observacao_operador: null,
    atualizado_em: null,
    atualizado_por: null,
    local_separacao: null,
    prazo_limite: null,
    prioridade: "Urgente",
    observacoes: null,
    foto_nome: null,
    foto_data_url: null,
    empilhadeira_id: null,
    empilhadeira_identificacao: null,
    status: "Aguardando",
    operador_nome: null,
    criado_em: new Date(now - 1000 * 60 * 70).toISOString(),
    assumido_em: null,
    a_caminho_em: null,
    cheguei_em: null,
    iniciado_em: null,
    finalizado_em: null,
    cancelado_em: null,
  },
  {
    id: "c2",
    categoria: "operacional",
    empresa_id: "empresa-1",
    supermercado_id: "super-1",
    solicitante_nome: "Bia",
    setor: "Estoque",
    local_exato: null,
    tipo_servico: "Movimentação",
    numero_pedido: null,
    cliente: null,
    produto: null,
    quantidade: null,
    itens: [],
    total_solicitado: null,
    total_encontrado: null,
    percentual_atendido: null,
    motivo_incompleto: null,
    observacao_operador: null,
    atualizado_em: null,
    atualizado_por: null,
    local_separacao: null,
    prazo_limite: null,
    prioridade: "Normal",
    observacoes: null,
    foto_nome: null,
    foto_data_url: null,
    empilhadeira_id: null,
    empilhadeira_identificacao: null,
    status: "Aguardando",
    operador_nome: null,
    criado_em: new Date(now - 1000 * 60 * 50).toISOString(),
    assumido_em: null,
    a_caminho_em: null,
    cheguei_em: null,
    iniciado_em: null,
    finalizado_em: null,
    cancelado_em: null,
  },
  {
    id: "c3",
    categoria: "operacional",
    empresa_id: "empresa-1",
    supermercado_id: "super-2",
    solicitante_nome: "Cleo",
    setor: "Recebimento",
    local_exato: null,
    tipo_servico: "Descarga",
    numero_pedido: null,
    cliente: null,
    produto: null,
    quantidade: null,
    itens: [],
    total_solicitado: null,
    total_encontrado: null,
    percentual_atendido: null,
    motivo_incompleto: null,
    observacao_operador: null,
    atualizado_em: null,
    atualizado_por: null,
    local_separacao: null,
    prazo_limite: null,
    prioridade: "Normal",
    observacoes: null,
    foto_nome: null,
    foto_data_url: null,
    empilhadeira_id: null,
    empilhadeira_identificacao: null,
    status: "Em atendimento",
    operador_nome: "Dino",
    criado_em: new Date(now - 1000 * 60 * 140).toISOString(),
    assumido_em: new Date(now - 1000 * 60 * 120).toISOString(),
    a_caminho_em: null,
    cheguei_em: null,
    iniciado_em: new Date(now - 1000 * 60 * 130).toISOString(),
    finalizado_em: null,
    cancelado_em: null,
  },
];

test("getOperationalActionPlan prioriza ação para urgentes e fila sem operador", () => {
  const plan = getOperationalActionPlan(chamados);

  assert.equal(plan.length >= 2, true);
  assert.equal(plan[0].priority, "high");
  assert.match(plan[0].title, /urgente|prioridade/i);
  assert.equal(plan[1].priority, "medium");
});
